### ISSUE TITLE
tests don't fail on CI when xmgrace is not installed

### ISSUE THREAD

**Issue by mmckerns** [uqfoundation/pygrace#2]
```
$ for test in pygrace/tests/test_*.py; do echo $test ; if [[ $COVERAGE == "true" ]]; then coverage run -a $test > /dev/null; else python $test > /dev/null; fi ; done
pygrace/tests/test_interactive.py
test_grace__getattr__ (__main__.PyGrace_PyGrace_TestCase)
grace: call grace method if gracePlot method is implicit ... Process: could not start xmgrace
ok
test_grace_exists (__main__.PyGrace_PyGrace_TestCase)
grace: check if grace variable exists ... Process: could not start xmgrace
ERROR

...[snip]...

======================================================================
ERROR: test_graceput (__main__.PyGrace_PyGrace_TestCase)
grace: pass a variable into grace
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.15/lib/python3.7/site-packages/pygrace/interactive/process.py", line 157, in flush
    self.pipe.flush()
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pygrace/tests/test_interactive.py", line 33, in tearDown
    self.session.exit()
  File "/home/travis/virtualenv/python3.7.15/lib/python3.7/site-packages/pygrace/interactive/project.py", line 99, in exit
    self.grace.exit()
  File "/home/travis/virtualenv/python3.7.15/lib/python3.7/site-packages/pygrace/interactive/process.py", line 209, in exit
    self('exit') # also flushes the queue
  File "/home/travis/virtualenv/python3.7.15/lib/python3.7/site-packages/pygrace/interactive/process.py", line 169, in __call__
    self.flush()
  File "/home/travis/virtualenv/python3.7.15/lib/python3.7/site-packages/pygrace/interactive/process.py", line 161, in flush
    self.pipe.close()
BrokenPipeError: [Errno 32] Broken pipe

----------------------------------------------------------------------
Ran 18 tests in 18.124s

FAILED (errors=7)
```

**Comment by mmckerns** [comment]
skip 'session' tests if `xmgrace` not installed done in: fbc4a72d922b0fa06562ebf81dc3ce45c43b7138
